title = "Common Gitleaks Config"

[allowlist]
paths = [
  '''target/''',
  '''build/''',
  '''node_modules/'''
]

[[rules]]
id = "config-password"
description = "Detect hardcoded passwords in configuration files"

regex = '''(?im)^(?!\s*(#|//)).*\b(password|passwd|pwd)\b\s*[:=]\s*([^\s#]+)'''
secretGroup = 3

keywords = [
  "password",
  "passwd",
  "pwd"
]
