title = "Common Gitleaks Config"

[allowlist]
paths = [
  '''target/''',
  '''build/''',
  '''.git/''',
  '''node_modules/'''
]

[[rules]]
id = "config-password"
description = "Hardcoded password in configuration file"

regex = '''(?im)^(?!\s*(#|//)).*\b(password|passwd|pwd)\b\s*[:=]\s*([^\s#]+)'''
secretGroup = 3

keywords = [
  "password",
  "passwd",
  "pwd"
]

[rules.allowlist]
regexes = [
  '''MVNW_PASSWORD''',
  '''@SET MVNW_PASSWORD''',
  '''has-password''',
  '''password\s[^\s*[:=]\s*["']?\*\}["']?'''
]
